### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by huehuw** [mlow/steam-library-updater#2]
After running the application in docker I get the following error:
groupmod: GID '100' already exists

I haven't modified any of the settings other than entering in all the required steam information.

Is there something I am doing wrong?

**Comment by mlow** [comment]
It would seem that the group ID of your steam directory is 100. `entrypoint.sh` attempts to change the `steam` group ID to that of  the steam directory, but in this case that group already exists in the container resulting in the error. I'll try to take a look at this soon. In the meantime, if you changed the owner/group of your steam directory to something 1000+,  it should work.

**Comment by huehuw** [comment]
Tried changing it to 1001 but still gives the same error unfortunately. I also tried changing the ID of the folder itself and that also didnt work

**Comment by mlow** [comment]
Hi @huehuw this should be fixed now, the way privileges are dropped in `entrypoint.sh` has been updated. Look forwarding to hearing if it works for you now!

**Comment by huehuw** [comment]
hey mate still getting the same error, could it have something to do with the fact that I am running it on a Synology Nas?

**Comment by huehuw** [comment]
Okay so after redownloading and installing from scratch it has gotten a little further this time:
![Steam Downloader Error](https://user-images.githubusercontent.com/77577934/229803827-f49e5520-2f97-4e37-bf96-2fec7c824241.png)

**Comment by huehuw** [comment]
It crashes at that point above^

**Comment by mlow** [comment]
@huehuw  Seems to be the exact same issue as  https://github.com/ValveSoftware/steam-for-linux/issues/7190

Curious, are you able to run the [steamcmd/steamcmd](https://hub.docker.com/r/steamcmd/steamcmd) image directly?
